In [ ]:
#nummpy manipulation

In [3]:
#numpy range(20)
import numpy as np

x = np.arange(20)
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x = np.full((3,3),True,dtype=bool)
#or
y = np.full((9),True,dtype=bool).reshape(3,3)
#or
z = np.ones((3,3),dtype=bool)

x.all() is y.all()



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
arr = np.arange(20)
print(arr[arr%2 == 1])
arr[arr%2 == 1] = -1
arr

[ 1  3  5  7  9 11 13 15 17 19]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

In [27]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])

# Solution

arr = np.arange(10)
print(arr.reshape(2,5))

# Another solution
arr = np.arange(10)
print(arr.reshape(2, -1))  # Setting to -1 automatically decides the number of cols

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

# Solution

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


# Solution:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [30]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


# Solution

a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

#other solution
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [33]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])


# Solution:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [32]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])


# Solution
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [34]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)


# Solution

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [35]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)


# Solution

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [36]:
# Question: Convert the function maxx that works on two scalars, to work on two arrays.
# Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# maxx(1, 5)
#> 5

# Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# Solution

def pair_max(x, y):
    # here I am using map to make tuple from a and b, other solution is using zip(a,b)
    maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b),x,y)]
    # using zip
    # maximum = [maxx(a,b) for a,b in zip(x,y)]
    return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [39]:
# Question: Swap columns 1 and 2 in the array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
print(arr)

# Solution

print("\nModified array")
arr[:, [1,0,2]]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [40]:
# Question: Swap rows 1 and 2 in the array arr:

# Input: 

arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)

# Solution

print("\nModified array")
arr[[1,0,2], :]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [41]:
# Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[::-1, :]

Original array

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [42]:
# Question: Reverse the columns of a 2D array arr.

# Input: arr = np.arange(9).reshape(3,3)

# Solution

arr = np.arange(9).reshape(3,3)
print('Original array')
arr


print("\nModified array")
arr[:, ::-1]

Original array

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [43]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:

rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[7.43458996, 5.41590246, 6.25652672],
       [9.07377641, 7.1141124 , 6.52866146],
       [9.61079104, 6.65625657, 8.9077415 ],
       [7.92523372, 8.61756441, 6.79848807],
       [8.95393482, 9.35045401, 7.36355754]])

In [44]:
# Question: Print or show only 3 decimal places of the numpy array rand_arr.

# Input: rand_arr = np.random.random((5,3))

rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.007, 0.073, 0.267],
       [0.295, 0.361, 0.707],
       [0.518, 0.055, 0.257],
       [0.774, 0.106, 0.046],
       [0.258, 0.9  , 0.01 ]])

In [45]:
# Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input: 
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
rand_arr

# Output:
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

np.set_printoptions(suppress=True)
rand_arr
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

In [47]:
# Question: Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=7)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [48]:
# Question: Print the full numpy array a without truncating.

# Input: np.set_printoptions(threshold=6)
# a = np.arange(15)
# a

# Output: a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution

a = np.arange(15)


np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])